config/routes.rb
Rails.application.routes.draw do

  root 'boards#home'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

   devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
    get 'boards',to: "boards#index"
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get '/users/:id', to: 'users#show', as: 'user'

    resources :boards, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)

    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  name                   :string(255)      default(""), not null
#  profile                :text(65535)
#  profile_photo          :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,length: { maximum: 8 }
  validates :email,length: { maximum: 50 }

  has_one_attached :avatar
  has_many :comments
  has_many :likes
  has_many :boards, dependent: :destroy


  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得

  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         validates :profile,length: { maximum: 200 }
         validates :email, presence: true


         def update_without_current_password(params, *options)
          params.delete(:current_password)

          if params[:password].blank? && params[:password_confirmation].blank?
            params.delete(:password)
            params.delete(:password_confirmation)
          end

          result = update_attributes(params, *options)
          clean_up_passwords
          result
        end

         def self.guest
         find_or_create_by!(email: 'guest@example.com') do |user|
         user.password = SecureRandom.urlsafe_base64
        # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
         end
        end

        # ユーザーをフォローする
        def follow(user_id)
        follower.create(followed_id: user_id)
        end

        # ユーザーのフォローを外す
        def unfollow(user_id)
        follower.find_by(followed_id: user_id).destroy
        end

        # フォローしていればtrueを返す
        def following?(user)
        following_user.include?(user)
        end
   end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController


  def new_guest
    user = User.guest
    sign_in user
    redirect_to boards_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find_by(id: params[:id])
        @board = Board.find_by(id: params[:id])
      end
    end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/users/show.html.erb
<% provide(:title, "The person") %>
  <div class="row">
    <div class="col-md-4 text-center">
     <% if @user.avatar.attached? %>
      <%= image_tag (@user.avatar),class: "round-img" %>
      <% else %>
     <%= image_tag avatar_url(@user), class: "round-img" %>
      <% end %>
    </div>
    <div class="col-md-8 user-center">
      <div class="row">
        <h1 class="user-name"><%= @user.name %></h1>

        <p class="profile-edit"><%= @user.profile %></p>


        <% if @user == current_user %>
          <h1 class="user-profile-edit"><%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark edit-profile-btn" %></h1>
          <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% end %>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
      </div>

<div class="follow-container">
<h1 class="follow-right"><%= "フォロー #{@user.follower.count}" %></h1>
<h1 class="follow-left"><%= "フォロワー #{@user.followed.count}" %></h1>
</div>
<% unless @user == current_user %>
  <% if current_user.following?(@user) %>
    <%= link_to 'フォロー解除', unfollow_path(@user.id), method: :POST,class:"follow-link" %>
  <% else %>
    <%= link_to 'フォロー', follow_path(@user.id), method: :POST,class:"follow-link" %>
  <% end %>
<% end %>
  <div class="media-body">
  </div>
      </div>
    </div>
  </div>
  <%= render 'partial/footer' %>
</div>