config/routes.rb
Rails.application.routes.draw do

  root 'boards#home'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

   devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
    get 'boards',to: "boards#index"
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get '/users/:id', to: 'users#show', as: 'user'

    resources :boards, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)

    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  caption    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Board < ApplicationRecord
  validates :caption, presence: true, length:{ maximum: 15}
  has_one_attached :avatar
  belongs_to :user

  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos
  def liked_by(current_user)
    Like.find_by(user_id: current_user.id, board_id: id)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # skip_before_action :method_name, raise: false
    before_action :authenticate_user!,except: [:home]
    before_action :set_board, only: %i(show destroy)

    def home
    end

    def index
      @boards = Board.order(created_at: :desc).page(params[:page]).per(5)
    end

    def new

        @board = Board.new
        @board.photos.build

    end

    def create
        @board = Board.new(board_params)
        if @board.photos.present?
          @board.save
          redirect_to boards_path
          flash[:notice] = "投稿が保存されました"
        else
          redirect_to boards_path
          flash[:alert] = "投稿に失敗しました"
    end
  end

    def show

    end

    def destroy
        if @board.user == current_user
            flash[:notice] = "投稿が削除されました" if @board.destroy
        else
            flash[:alert] = "投稿の削除に失敗しました"
        end
        redirect_to boards_path
    end


    private
    def board_params
      params.require(:board).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
    end

    def set_board
        @board = Board.find_by(id: params[:id])
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_comment_list.html.erb
<% board.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", board_comment_path(board.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span class="comment_size"><%= comment.comment %></span>
  </div>
<% end %>

app/views/boards/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/boards/home.html.erb
<% provide(:title, "Home") %>
<div class="container container-left">
<div class="header-logo">
<header class="page-header">
      <h1><%= image_tag 'logo_music.png',class:"logo" %><h1>
</header>
</div>


<%# メイン画面　%>
<div class="home big-bg">
  <div class="home-content wrapper">
      <h2 class="page-title">Welcome Musicgram!</h2>
      <p>あなたのおすすめの<br>アーティストを共有しよう!</p>
      <p><%= link_to "登録する", new_user_registration_path,class:"btn" %></p>
     </div>
</div>
</div>
<%# 説明概要　%>
<h2 class="focus-title">MusicAppとは?</h2>
<div class="content-about">
 <h1><%= image_tag 'home.png',class:"bish_logo" %></h1>
 <p class="focus">他のユーザのおすすめアーティストを<br>共有できいいねやコメントを残せます!</p>
 <h1><%= image_tag 'guest.png',class:"guest_logo" %></h1>
 <p class="description">登録しなくてもゲストログインをして機能を<br>確認することができます♪</p>
</div>

<%= render 'partial/footer' %>
</div>

app/views/boards/index.html.erb
<% provide(:title, "Users") %>


<% @boards.each do |board| %>
  <div class="col-md-8 col-md-2 mx-auto mx-coloum">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">


          <%= link_to user_path(board.user), class: "black-color no-text-decoration",
            title: board.user.name do %>
            <strong><%= board.user.name %></strong>
          <% end %>

          <% if board.user_id == current_user.id %>
            <%= link_to board_path(board), method: :delete, class: "ml-auto mx-0 my-auto" do %>
              <div class="delete-post-icon">
              </div>
            <% end %>
          <% end %>

        </div>


          <%= image_tag board.photos.first.image.url(:medium), class: "card-img-top" %>


        <div class="card-body">
          <div class="row parts">

            <div id="like-icon-post-<%= board.id.to_s %>">
              <% if board.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", board_like_path(board.id, board.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", board_likes_path(board), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>

            <%= link_to "", "#", class: "comment" %>
          </div>

          <div id="like-text-post-<%= board.id.to_s %>">
            <%= render "like_text", { likes: board.likes } %>
          </div>

          <div>
          <div class="user-caption-board">
            <span class="user-name-board"><strong><%= board.user.name %></strong></span>
            <span class="board-caption"><%= board.caption %></span>
            <%= link_to time_ago_in_words(board.created_at).upcase + "前", board_path(board), class: "post-time no-text-decoration" %>
          </div>
           <div class="comment-board">
            <div id="comment-post-<%= board.id.to_s %>">
              <%= render 'comment_list', { board: board } %>
            </div>
            <%= link_to time_ago_in_words(board.created_at).upcase + "前", board_path(board),
              class: "light-color post-time no-text-decoration" %>
              </div>
            <hr>
            <div class="row actions" id="comment-form-post-<%= board.id.to_s %>">
              <%= form_with model: [board, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :board_id, value: board.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= paginate @boards %>
<%= render 'partial/footer' %>

app/views/boards/new.html.erb
<% provide(:title, "New") %>
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @board, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">


            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "アーティスト名" %>
            </div>
          </div>
          <div class="mb-3">

            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image,class: "file-form file_image_button"  %>
            <% end %>

          </div>
          <%= f.submit "投稿する", class: "btn btn-primary btn-form " %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'partial/footer' %>

app/views/boards/show.html.erb
<% provide(:title, "User") %>
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @board.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@board.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@board.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@board.user), class: "black-color no-text-decoration post-user-name",
              title: @board.user.name do %>
              <strong><%= @board.user.name %></strong>
            <% end %>

             <% if @board.user_id == current_user.id %>
              <%= link_to board_path(@board), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @board.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
            <div id="comment-post-<%= @board.id.to_s %>">
                <%= render 'comment_list', board: @board %>
              </div>
            </div>
          </div>
        </div>
        <div class="row parts">
         <div id="like-icon-post-<%= @board.id.to_s %>">
            <% if @board.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", board_like_path(@board.id, @board.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", board_likes_path(@board), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>
        </div>
        <div id="like-text-post-<%= @board.id.to_s %>">
          <%= render "like_text", { likes: @board.likes } %>
        </div>
        <div class="post-time"><%= time_ago_in_words(@board.created_at).upcase %>前</div>
        <hr>
        <div class="row parts" id="comment-form-post-<%= @board.id.to_s %>">
          <%= form_with model: [@board, Comment.new],  class: "w-100" do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :board_id, value: @board.id %>
            <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'partial/footer' %>